obj-$(CONFIG_SPSLR) += spslr.o spslr_env.o spslr_randomizer.o

CFLAGS_REMOVE_spslr.o += $(SPSLR_PLUGIN_FLAGS)
CFLAGS_REMOVE_spslr_env.o += $(SPSLR_PLUGIN_FLAGS)
CFLAGS_REMOVE_spslr_randomizer.o += $(SPSLR_PLUGIN_FLAGS)
