#ifndef SPSLR_LIST_H
#define SPSLR_LIST_H

#define SPSLR_IPIN_OP_PATCH 1
#define SPSLR_IPIN_OP_ADD_INITIAL_OFFSET 2
#define SPSLR_IPIN_OP_SUB_INITIAL_OFFSET 3
#define SPSLR_IPIN_OP_ADD_OFFSET 4
#define SPSLR_IPIN_OP_SUB_OFFSET 5
#define SPSLR_IPIN_OP_ADD_CONST 6

#define SPSLR_FLAG_FIELD_FIXED 1

#endif
